Use Shell instead of Core_extended.Shell
In summary, the `Core_extended.Shell` seems to have been moved to its
own library `shell`.
See https://discuss.ocaml.org/t/ann-v0-12-release-of-jane-street-packages/3499

The `core_extended` library https://github.com/janestreet/core_extended
has reorganised their code
https://discuss.ocaml.org/t/ann-v0-12-release-of-jane-street-packages/3499

While trying the `github_org_info` example I ran into the following
problem:

```
dune exec -- ./github_org_info.exe janestreet
File "dune", line 15, characters 32-45:
15 |   (libraries core yojson atdgen core_extended)
                                     ^^^^^^^^^^^^^
Error: Library "core_extended" not found.
Hint: try: dune external-lib-deps --missing ./github_org_info.exe
```

Similar to https://github.com/janestreet/core_extended/issues/22 the
`core_extended` library was installed:

```
$ ocamlfind list | grep core_extended
core_extended       (version: n/a)
core_extended.base64 (version: v0.12.0)
core_extended.delimited_kernel (version: v0.12.0)
core_extended.find_files (version: v0.12.0)
core_extended.selection (version: v0.12.0)

$ dune installed-libraries | grep core_extended
core_extended.base64                    (version: v0.12.0)
core_extended.delimited_kernel          (version: v0.12.0)
core_extended.find_files                (version: v0.12.0)
core_extended.selection                 (version: v0.12.0)
```

The solution has been to install the `shell` library and use the `Shell`
module instead of `Core_extended.Shell`.

Signed-off-by: Arnau Siches <asiches@gmail.com>